server:
  port: 17075
  ssl:
    key-store: classpath:sandglass.js.cn.pfx
    key-store-password: 214938487690629
    keyStoreType: PKCS12
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sandglassfinance?characterEncoding=utf8&serverTimezone=Asia/Shanghai&autoReconnect=true&failOverReadOnly=false&rewriteBatchedStatements=true
  redis:
    host: redis
    port: 6379