spring:
  profiles:
    active: dev # 运行环境
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13304/sandglassfinance?serverTimezone=Asia/Shanghai # 数据库地址 时区为上海时间
    username: root
    password: sandglassfinance_MySql_password+-
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 运行时输出sql语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 数据库方言
  jackson:
    time-zone: GMT+8 # 时区
  redis: # redis缓存
    database: 0
    host: 127.0.0.1
    port: 16379
    password: suichu_redis_password+-

server:
  port: 443 # 服务器端口
  ssl: # https配置
    key-store: classpath:sandglass.js.cn.pfx
    key-store-password: 214938487690629
    keyStoreType: PKCS12
  servlet:
    context-path: /api/v1 # 接口前置url
ssb: # 第三方登录配置
  security:
    social:
      wechat: # 微信
        app-id: wx3b0c244789896cce
        app-secret: ddb4faa8414920750c6845fe9737b69e
        provider-id: wechat

# Redis数据库索引（默认为0）
  spring.redis.database=0
  # Redis服务器地址
  spring.redis.host=172.31.19.222
  # Redis服务器连接端口
  spring.redis.port=6379
  # Redis服务器连接密码（默认为空）
  spring.redis.password=
  # 连接池最大连接数（使用负值表示没有限制）
  spring.redis.pool.max-active=8
  # 连接池最大阻塞等待时间（使用负值表示没有限制）
  spring.redis.pool.max-wait=-1
  # 连接池中的最大空闲连接
  spring.redis.pool.max-idle=8
  # 连接池中的最小空闲连接
  spring.redis.pool.min-idle=0
  # 连接超时时间（毫秒）
  spring.redis.timeout=0
