spring:
  profiles:
    active: dev # 运行环境
  datasource: # 数据库配置
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13304/sandglassfinance?serverTimezone=Asia/Shanghai # 数据库地址 时区为上海时间
    username: root
    password: sandglassfinance_MySql_password+-
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true # 运行时输出sql语句
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect # 数据库方言
  jackson:
    time-zone: GMT+8 # 时区
  redis: # redis缓存
    database: 0
    host: 127.0.0.1
    port: 16379
    password: sandglassfinance_Redis_password+-
    timeout: 10000
    jedis:
      pool:
        max-active: 100
        max-wait: -1
        max-idle: 10
        min-idle: 0
server:
  port: 443 # 服务器端口
  ssl: # https配置
    key-store: classpath:sandglass.js.cn.pfx
    key-store-password: 214938487690629
    keyStoreType: PKCS12
  servlet:
    context-path: /api/v1 # 接口前置url
security:
  oauth2:
    client:
      client-id: ea12a1c0-f9f7-11e8-9295-0242ac120002
      client-secret: da3b6a5efeb4a87be4742be07161766d52f91991
ssb: # 第三方登录配置
  security:
    social:
      wechat: # 微信
        app-id: wx3b0c244789896cce
        app-secret: ddb4faa8414920750c6845fe9737b69e
        provider-id: wechat
swagger2: # api文档
  enable: true
user: # 用户密码加密
  salt: sandglassfinance_password_SALT_+++++++++++---------------------- # 盐