server:
  port: 17075
  ssl:
    key-store: classpath:sandglass.js.cn.pfx
    key-store-password: 214938487690629
    keyStoreType: PKCS12
spring:
  datasource:
    url: jdbc:mysql://mysql:3306/sandglassfinance?serverTimezone=Asia/Shanghai
  redis:
    database: 0
    host: redis
    port: 6379
    password: suichu_redis_password+-