spring:
  profiles:
    active: dev
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:13304/sandglassfinance?serverTimezone=Asia/Shanghai
    username: root
    password: sandglassfinance_MySql_password+-
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
  jackson:
    time-zone: GMT+8
server:
  port: 443
  ssl:
    key-store: classpath:sandglass.js.cn.pfx
    key-store-password: 214938487690629
    keyStoreType: PKCS12
  servlet:
    context-path: /api/v1