FROM mysql:5.7
#设置免密登录 
ENV MYSQL_ROOT_PASSWORD sandglassfinance_MySql_password+-
ENV MYSQL_DATABASE sandglassfinance
ENV LANG C.UTF-8
#将所需文件放到容器中 
COPY ./conf.d /etc/mysql/conf.d
COPY ./sql /sql
COPY ./set.sh /set.sh
#设置容器启动时执行的命令 
# CMD ["sh", "/mysql/setup.sh"]